version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    restart: always
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend/
    container_name: backend
    restart: always
    ports:
      - "5100:5100"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
